### ISSUE TITLE
Lemmy => Mastodon does not do anything

### ISSUE THREAD

**Issue by JohnnyJayJay** [ManeraKai/fediredirect#4]
Hi! First of all, love that someone is making this extension. It's something I was really looking for.

Unfortunately, the Lemmy => Mastodon Redirect does not work for me. When I click the button, nothing happens (as far as I can tell).

I have set up the Mastodon connection in the settings. I authorised the extension and copied over the code. My Mastodon instance is https://chaos.social, my Lemmy instance is https://feddit.de. The redirect does not work regardless of post or instance.

**Comment by ManeraKai** [comment]
I improved the UI recently to tell which things can redirect and which things can't.
As of right now, the only think that can redirect Lemmy => Mastodon are users profiles and community pages. Yes if you subscribe to a community or a user from Lemmy you can see his posts in your mastodon feed, but interestingly you can't "search" about him. It's still not implemented on Mastodon side yet.

**Comment by ManeraKai** [comment]
oh one second yes it's working now. Alright I'll implement it :)
