### ISSUE TITLE
Add PeerTube support

### ISSUE THREAD

**Issue by jeena** [ManeraKai/fediredirect#5]
PeerTube has the same problem as this solves for both Mastodon and Lemmy, it would be cool to have support for PeerTube in the same extension too.

**Comment by ManeraKai** [comment]
The only thing I still couldn't figure to work is peertube video => peertube video.
Everything else is implemented, now you can comment on a peertube video from your mastodon account by a simple redirect button :)

**Comment by jeena** [comment]
Yeah for some reason if you don't use the search first then just replacing the domain part of the URL doesn't work and you get a 404 on your instance. The only workaround would be probably to redirect to your instances search?

But great thanks for all the effort!

**Comment by ManeraKai** [comment]
Give me an example link.

**Comment by jeena** [comment]
https://tilvids.com/w/9adnadXqoWYbbKGNQrc6Fj -> https://toot.jeena.net/w/9adnadXqoWYbbKGNQrc6Fj will not work because I haven't searched for this one on my instance before so my instance is not aware of it's existence.

https://tilvids.com/w/u2pBk5Vdg85FWhTmXZQaUA -> https://toot.jeena.net/w/u2pBk5Vdg85FWhTmXZQaUA will work because I did search for it so my instance is aware of it.

And here is the search for the first one:

https://tilvids.com/w/9adnadXqoWYbbKGNQrc6Fj -> https://tube.jeena.net/search?search=https:%2F%2Ftilvids.com%2Fw%2F9adnadXqoWYbbKGNQrc6Fj

So in the end the search should be something like https://${domain}/search?search=https:%2F%2Ftilvids.com%2Fw%2F${uid}

**Comment by ManeraKai** [comment]
When I said:
> The only thing I still couldn't figure to work is peertube video => peertube video.

I meant the search. I won't redirect to a search domain name rather I'll make the search be processed without the user noticing.

**Comment by ManeraKai** [comment]
https://github.com/ManeraKai/fediredirect/assets/40805353/c036f09b-7ca9-4e40-a2a2-87d77faf02b2
